"""Application constants and display labels."""

from __future__ import annotations

APP_NAME = "Quiz Wizard"
APP_VERSION = "2.0.0"
POINTS_PER_CORRECT = 10
AUTO_STREAK_THRESHOLD = 3
QUESTIONS_PER_BANK = 20

# Internal keys
CATEGORY_GENERAL = "general_knowledge"
CATEGORY_TECHNICAL = "technical"
CATEGORY_GEOPOLITICAL = "geopolitical"

DIFFICULTY_EASY = "easy"
DIFFICULTY_MEDIUM = "medium"
DIFFICULTY_HARD = "hard"
DIFFICULTY_AUTO = "auto"

CATEGORIES = (
    CATEGORY_GENERAL,
    CATEGORY_TECHNICAL,
    CATEGORY_GEOPOLITICAL,
)

DIFFICULTIES = (
    DIFFICULTY_EASY,
    DIFFICULTY_MEDIUM,
    DIFFICULTY_HARD,
)

CATEGORY_LABELS = {
    CATEGORY_GENERAL: "General Knowledge",
    CATEGORY_TECHNICAL: "Technical",
    CATEGORY_GEOPOLITICAL: "Geopolitical",
}

DIFFICULTY_LABELS = {
    DIFFICULTY_EASY: "Easy",
    DIFFICULTY_MEDIUM: "Medium",
    DIFFICULTY_HARD: "Hard",
    DIFFICULTY_AUTO: "Auto",
}

# Legacy V1 filename stems → (category, difficulty)
LEGACY_FILE_MAP = {
    "gene": (CATEGORY_GENERAL, DIFFICULTY_EASY),
    "genm": (CATEGORY_GENERAL, DIFFICULTY_MEDIUM),
    "genh": (CATEGORY_GENERAL, DIFFICULTY_HARD),
    "teche": (CATEGORY_TECHNICAL, DIFFICULTY_EASY),
    "techm": (CATEGORY_TECHNICAL, DIFFICULTY_MEDIUM),
    "techh": (CATEGORY_TECHNICAL, DIFFICULTY_HARD),
    "geoe": (CATEGORY_GEOPOLITICAL, DIFFICULTY_EASY),
    "geom": (CATEGORY_GEOPOLITICAL, DIFFICULTY_MEDIUM),
    "geoh": (CATEGORY_GEOPOLITICAL, DIFFICULTY_HARD),
}

DEFAULT_WINDOW_SIZE = "1100x700"
MIN_WINDOW_SIZE = (900, 600)
